steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/'
      - '--build-arg'
      - 'NEXT_PUBLIC_VNC_BROWSER_URL=wss://vnc-browser-service-644185288504.us-central1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_EXTENSION_BACKEND_URL=https://extension-backend-service-644185288504.us-central1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_MAIN_BACKEND_URL=https://backend-api-644185288504.us-central1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_OMNIPARSER_URL=https://omniparser-service-644185288504.us-central1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_LANGGRAPH_URL=${_NEXT_PUBLIC_LANGGRAPH_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_LANGGRAPH_API_KEY=${_NEXT_PUBLIC_LANGGRAPH_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'CLERK_SECRET_KEY=${_CLERK_SECRET_KEY},NEXT_PUBLIC_EXTENSION_BACKEND_URL=https://extension-backend-service-644185288504.us-central1.run.app,NEXT_PUBLIC_MAIN_BACKEND_URL=https://backend-api-644185288504.us-central1.run.app,NEXT_PUBLIC_OMNIPARSER_URL=https://omniparser-service-644185288504.us-central1.run.app,NEXT_PUBLIC_VNC_BROWSER_URL=wss://vnc-browser-service-644185288504.us-central1.run.app,NEXT_PUBLIC_LANGGRAPH_URL=${_NEXT_PUBLIC_LANGGRAPH_URL},NEXT_PUBLIC_LANGGRAPH_API_KEY=${_NEXT_PUBLIC_LANGGRAPH_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/frontend:latest'

timeout: 1200s
